### ISSUE TITLE
Not following HTTP redirect

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#15]
I am trying to learn how to create packages and so I just copied pip.pypa.org into my own project folder and ran it. I'm not sure why I got this error when it's obviously working for you guys. Anyway I debugged it and thought maybe there is an issue after all.

```
{ ignoring: "1.5.1rc1", reason: "unparsable" }
{ ignoring: "10.0.0b1", reason: "unparsable" }
{ ignoring: "10.0.0b2", reason: "unparsable" }
{ ignoring: "20.1b1", reason: "unparsable" }
{ ignoring: "20.2b1", reason: "unparsable" }
{ ignoring: "20.3b1", reason: "unparsable" }
{ ignoring: "22.1b1", reason: "unparsable" }
downloading
downloading
error: Uncaught (in promise) Error: 404: https://github.com/pypa/pip/archive/refs/tags/22.3.1.tar.gz
    throw new TeaError('http', {underr, ...opts})
          ^
    at download (file:///Users/u0076374/Dropbox/Github/Tea/pantry.core/src/hooks/useDownload.ts:104:11)
    at async file:///Users/u0076374/Dropbox/Github/Tea/pantry.core/scripts/fetch.ts:40:14
    at async fetch_src (file:///Users/u0076374/Dropbox/Github/Tea/pantry.core/scripts/fetch.ts:33:19)
    at async __build (file:///Users/u0076374/Dropbox/Github/Tea/pantry.core/scripts/build/build.ts:34:30)
    at async _build (file:///Users/u0076374/Dropbox/Github/Tea/pantry.core/scripts/build/build.ts:22:12)
    at async file:///Users/u0076374/Dropbox/Github/Tea/pantry.core/scripts/build.ts:47:3
```

Debugging: `curl -D - https://github.com/pypa/pip/archive/refs/tags/22.3.1.tar.gz` produced a "HTTP/1.1 302 Found" with the location header "Location: https://codeload.github.com/pypa/pip/tar.gz/refs/tags/22.3.1". If I replace the "distributable" -> "url"  with that location then it builds.

I'm guessing that tea isn't following the redirect.

(edit to remove the sudo prompt comment, which is described in a different issue.)

**Comment by magnusviri** [comment]
I just tried to build another package and it got errors too. Are we supposed to be able to build these packages on our own?

**Comment by magnusviri** [comment]
I will post a new issue regarding the sudo prompt because it happened with another package. I'll limit this one to the HTTP redirect.

**Comment by magnusviri** [comment]
It turned out that the github token was causing the error. I didn't give the token any permissions and it needed "repo" -> "public_repo". I updated the [wiki](https://github.com/teaxyz/pantry.zero/wiki#personal-access-token) with this information. I thought of where to put in an error code but the best/worst place to put it is in the cli repo in [useDownload.ts](https://github.com/teaxyz/cli/blob/main/src/hooks/useDownload.ts#L114). It's the best place because it has the most information but it's the worst because I don't know what else uses this file so a specific error could be misleading if it were called from a different location.

Anyway, I'm going to close this. If it would help to add an error message about this, just re-open it and tell me where to put it and I'll do my best.
