### ISSUE TITLE
/opt/tea/tea.xyz/var/pantry/scripts/brewkit/fix-machos.rb wants sudo password.

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#16]
I am simultaneously trying to create a package for the python project I work on, and I'm trying to document this process in the [wiki](https://github.com/teaxyz/pantry.zero/wiki).

I thought I would start with the simplest of package.yml files just to see how this works. So [here it is](https://github.com/magnusviri/pantry.magnusviri.extra/blob/main/projects/utah.edu/jctl/package.yml). I got to the point that it's asking for a sudo password. If I cntl-c I can see the stacktrace points to /opt/tea/tea.xyz/var/pantry/scripts/brewkit/fix-machos.rb. Edit to add, I remember reading somewhere that the Mach-O binaries needed fixing and it requires this ruby script, I'm just hoping it can be installed sandboxed, without requiring sudo.

```
...
+ touch /opt/tea/utah.edu/jctl/v1.1.18/test


Your user account isn't allowed to install to the system RubyGems.
  You can cancel this installation and run:

      bundle install --path vendor/bundle

  to install the gems into ./vendor/bundle/, or you can enter your password
  and install the bundled gems to RubyGems using sudo.

  Password:
sudo: a password is required

/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/installer/parallel_installer.rb:201:in `handle_error': NoMethodError: undefined method `call' for "DEFAULT":String (Bundler::InstallError)
An error occurred while installing ruby-macho (3.0.0), and Bundler cannot continue.
Make sure that `gem install ruby-macho -v '3.0.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  ruby-macho
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/installer/parallel_installer.rb:106:in `call'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/installer/parallel_installer.rb:78:in `call'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/installer.rb:289:in `install_in_parallel'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/installer.rb:197:in `install'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/installer.rb:92:in `block in run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/process_lock.rb:19:in `rescue in lock'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/process_lock.rb:15:in `lock'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/installer.rb:73:in `run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/installer.rb:25:in `install'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/inline.rb:62:in `block in gemfile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/settings.rb:143:in `temporary'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/inline.rb:61:in `gemfile'
	from /opt/tea/tea.xyz/var/pantry/scripts/brewkit/fix-machos.rb:12:in `<main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/process_lock.rb:9:in `initialize': Permission denied @ rb_sysopen - /Library/Ruby/Gems/2.6.0/bundler.lock (Errno::EACCES)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/process_lock.rb:9:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/process_lock.rb:9:in `lock'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/installer.rb:73:in `run'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/installer.rb:25:in `install'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/inline.rb:62:in `block in gemfile'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/settings.rb:143:in `temporary'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/bundler/inline.rb:61:in `gemfile'
	from /opt/tea/tea.xyz/var/pantry/scripts/brewkit/fix-machos.rb:12:in `<main>'
```

**Comment by magnusviri** [comment]
I just tried to build this in my [Docker container](https://github.com/magnusviri/pantry.magnusviri/blob/main/Dockerfile). That produces this error.

```
error: Uncaught (in promise) Error: couldn’t parse versions: utah.edu/jctl
    throw new Error(`couldn’t parse versions: ${pkg.str(spec)}`)
          ^
    at getVersions (file:///opt/build/pantry.core/src/hooks/usePantry.ts:199:11)
    at async Object.resolve (file:///opt/build/pantry.core/src/hooks/usePantry.ts:35:20)
    at async file:///opt/build/pantry.core/scripts/build.ts:46:15
```

**Comment by magnusviri** [comment]
Aha! This is [already an issue](https://github.com/teaxyz/pantry.core/issues/18). Closing this dup.
