### ISSUE TITLE
stable-diffusion-webui: ModuleNotFoundError: No module named 'fastapi'

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#1636]
```
+++ dirname /opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/bin/stable-diffusion-webui
++ cd /opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/bin/..
++ pwd
+ export install_dir=/opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29
+ install_dir=/opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29
+ export clone_dir=lib
+ clone_dir=lib
+ cd /opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/lib
+ source ./webui-macos-env.sh
+++ command -v python3.10
++ [[ -x /opt/tea/python.org/v3.10.11/bin/python3.10 ]]
++ python_cmd=python3.10
++ export install_dir=/Users/james
++ install_dir=/Users/james
++ export 'COMMANDLINE_ARGS=--skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate'
++ COMMANDLINE_ARGS='--skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate'
++ export 'TORCH_COMMAND=pip install torch==1.12.1 torchvision==0.13.1'
++ TORCH_COMMAND='pip install torch==1.12.1 torchvision==0.13.1'
++ export K_DIFFUSION_REPO=https://github.com/brkirch/k-diffusion.git
++ K_DIFFUSION_REPO=https://github.com/brkirch/k-diffusion.git
++ export K_DIFFUSION_COMMIT_HASH=51c9778f269cedb55a4d88c79c0246d35bdadb71
++ K_DIFFUSION_COMMIT_HASH=51c9778f269cedb55a4d88c79c0246d35bdadb71
++ export PYTORCH_ENABLE_MPS_FALLBACK=1
++ PYTORCH_ENABLE_MPS_FALLBACK=1
+ source ./webui-user.sh
++++ dirname /opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/bin/stable-diffusion-webui
+++ cd /opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/bin/..
+++ pwd
++ export install_dir=/opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29
++ install_dir=/opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29
++ export clone_dir=lib
++ clone_dir=lib
+ XDG=/Users/james/.local/share
+ mkdir -p /Users/james/.local/share/models/stable-diffusion /Users/james/.local/share/stable-diffusion-webui '/Users/james/Documents/Stable Diffusion WEBUI'
+ test -d /opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/lib/models/Stable-diffusion
+ test -d /opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/lib/extensions
+ test -d /opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/lib/outputs
+ CONFIG=/Users/james/.config/stable-diffusion-webui/config.json
+ test -f /Users/james/.config/stable-diffusion-webui/config.json
+ python ./launch.py --ui-config-file=/Users/james/.config/stable-diffusion-webui/config.json
Launching Web UI with arguments: --ui-config-file=/Users/james/.config/stable-diffusion-webui/config.json --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate
Traceback (most recent call last):
  File "/opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/lib/./launch.py", line 356, in <module>
    start()
  File "/opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/lib/./launch.py", line 347, in start
    import webui
  File "/opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/lib/webui.py", line 8, in <module>
    from fastapi import FastAPI
ModuleNotFoundError: No module named 'fastapi'
```

I have fastapi, so I don't know what's wrong.

ls -dl /opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/lib/venv/lib/python3.10/site-packages/fastapi

drwxr-xr-x@ 28 u0076374  wheel  896 Apr 20 12:05 /opt/tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v2023.3.29/lib/venv/lib/python3.10/site-packages/fastapi

**Comment by magnusviri** [comment]
I'm guessing the virtual environment isn't being activated.

**Comment by mxcl** [comment]
I imagine this is now fixed, can you confirm?

**Comment by magnusviri** [comment]
Yes, it's fixed. I got other errors though, but it worked, so I'm not sure the errors mattered. If I think they matter I'll open a new ticket.

**Comment by mxcl** [comment]
the other errors/warnings are known and don't seem to stop it from working at this time
