### ISSUE TITLE
+utah.edu/jctl

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#17]
I just tried to build my [test package](https://github.com/magnusviri/pantry.magnusviri.extra/blob/main/projects/utah.edu/jctl/package.yml) in my [Docker container](https://github.com/magnusviri/pantry.magnusviri/blob/main/Dockerfile). That produces this error.

```
error: Uncaught (in promise) Error: couldn’t parse versions: utah.edu/jctl
    throw new Error(`couldn’t parse versions: ${pkg.str(spec)}`)
          ^
    at getVersions (file:///opt/build/pantry.core/src/hooks/usePantry.ts:199:11)
    at async Object.resolve (file:///opt/build/pantry.core/src/hooks/usePantry.ts:35:20)
    at async file:///opt/build/pantry.core/scripts/build.ts:46:15
```

Any ideas?

(note, I first put this as a comment to a different issue but I figured it should be its own issue so I deleted the comment and created this issue.)

**Comment by magnusviri** [comment]
My bad! My package.yml was messed up. I fixed it and it finished! Yay!
