### ISSUE TITLE
+elm-lang.org

### ISSUE THREAD

**Issue by icidasset** [pkgxdev/pantry#171]
I'm in the process of adding [elm-lang.org](https://elm-lang.org), but getting stuck on the following:
```
error: Uncaught (in promise) Error: 404: https://github.com/elm/compiler/archive/refs/tags/0.19.1.tar.gz
    throw new TeaError('http', {cause, ...opts})
          ^
    at download (https://raw.githubusercontent.com/teaxyz/cli/v0.22.1/src/hooks/useDownload.ts:110:11)
    at async file:///Users/icid/Code/pantry.core/scripts/fetch.ts:45:14
    at async fetch_src (file:///Users/icid/Code/pantry.core/scripts/fetch.ts:38:19)
    at async file:///Users/icid/Code/pantry.core/scripts/fetch.ts:55:16
Caused by: Error: 404: https://github.com/elm/compiler/archive/refs/tags/0.19.1.tar.gz
    at internal (https://raw.githubusercontent.com/teaxyz/cli/v0.22.1/src/hooks/useDownload.ts:100:11)
    at async download (https://raw.githubusercontent.com/teaxyz/cli/v0.22.1/src/hooks/useDownload.ts:108:12)
    at async file:///Users/icid/Code/pantry.core/scripts/fetch.ts:45:14
    at async fetch_src (file:///Users/icid/Code/pantry.core/scripts/fetch.ts:38:19)
    at async file:///Users/icid/Code/pantry.core/scripts/fetch.ts:55:16
error: Uncaught (in promise) Error
  if (!status.success) throw new Error()
                             ^
    at fetch_src (file:///Users/icid/Code/pantry.core/scripts/build/build.ts:160:30)
    at async __build (file:///Users/icid/Code/pantry.core/scripts/build/build.ts:33:30)
    at async _build (file:///Users/icid/Code/pantry.core/scripts/build/build.ts:21:12)
    at async file:///Users/icid/Code/pantry.core/scripts/build.ts:45:11
```
It seems to treat the distribution url as a 404 while the url is actually available.
https://github.com/elm/compiler/archive/refs/tags/0.19.1.tar.gz

Any ideas? Thanks!

**Comment by icidasset** [comment]
Code: https://github.com/teaxyz/pantry.extra/compare/main...icidasset:pantry.extra:elm

**Comment by jhheider** [comment]
Intersting. Your WIP `package.yml` completes that part just fine (for me), and hangs up much later at:
```sh
+ cabal new-configure --ghc-option=-optl=-pthread
+ cabal new-build
Resolving dependencies...
Error: cabal: Could not resolve dependencies:
[__0] trying: elm-0.19.1 (user goal)
[__1] next goal: containers (dependency of elm)
[__1] rejecting: containers-0.6.5.1/installed-0.6.5.1 (conflict: elm =>
containers>=0.5.8.2 && <0.6)
[__1] skipping: containers-0.6.7, containers-0.6.6, containers-0.6.5.1,
containers-0.6.4.1, containers-0.6.3.1, containers-0.6.2.1,
containers-0.6.1.1, containers-0.6.0.1 (has the same characteristics that
caused the previous version to fail: excluded by constraint '>=0.5.8.2 &&
<0.6' from 'elm')
[__1] trying: containers-0.5.11.0
[__2] next goal: base (dependency of elm)
[__2] rejecting: base-4.16.3.0/installed-4.16.3.0 (conflict: containers =>
base>=4.3 && <4.16)
[__2] skipping: base-4.17.0.0, base-4.16.4.0, base-4.16.3.0, base-4.16.2.0,
base-4.16.1.0, base-4.16.0.0 (has the same characteristics that caused the
previous version to fail: excluded by constraint '>=4.3 && <4.16' from
'containers')
[__2] rejecting: base-4.15.1.0, base-4.15.0.0, base-4.14.3.0, base-4.14.2.0,
base-4.14.1.0, base-4.14.0.0, base-4.13.0.0, base-4.12.0.0, base-4.11.1.0,
base-4.11.0.0, base-4.10.1.0, base-4.10.0.0, base-4.9.1.0, base-4.9.0.0,
base-4.8.2.0, base-4.8.1.0, base-4.8.0.0, base-4.7.0.2, base-4.7.0.1,
base-4.7.0.0, base-4.6.0.1, base-4.6.0.0, base-4.5.1.0, base-4.5.0.0,
base-4.4.1.0, base-4.4.0.0, base-4.3.1.0, base-4.3.0.0, base-4.2.0.2,
base-4.2.0.1, base-4.2.0.0, base-4.1.0.0, base-4.0.0.0, base-3.0.3.2,
base-3.0.3.1 (constraint from non-upgradeable package requires installed
instance)
[__2] fail (backjumping, conflict set: base, containers, elm)
After searching the rest of the dependency tree exhaustively, these were the
goals I've had most trouble fulfilling: base, elm, containers
```

**Comment by mxcl** [comment]
we've had some issues with downloading for some people’s systems.

Does `curl -LO https://github.com/elm/compiler/archive/refs/tags/0.19.1.tar.gz` work for you?

Hypothesis: for some reason our code is getting an incorrect 404 for the above

**Comment by icidasset** [comment]
That curl command works yeah.

First I thought it might have been the crappy wifi/network I was on at the time.
But I just got home and I've removed `~/.tea` and reinstalled, but got the same thing.
Is there anything else I should reset? 🤔 

Interestingly, I now have tea version 0.22.2, yet the build script error still says 0.22.1
```
error: Uncaught (in promise) Error: 404: https://github.com/elm/compiler/archive/refs/tags/0.19.1.tar.gz
    throw new TeaError('http', {cause, ...opts})
          ^
    at download (https://raw.githubusercontent.com/teaxyz/cli/v0.22.1/src/hooks/useDownload.ts:110:11)
```
