### ISSUE TITLE
stable diffusion web-ui won't open

### ISSUE THREAD

**Issue by sanchitram1** [pkgxdev/pantry#1967]
Installed stable diffusion from the gui and tried to open it from there, and got this issue. 
```sh
Python 3.10.11 (main, Apr 20 2023, 20:33:22) [Clang 14.0.0 (clang-1400.0.29.202)]
Version: <none>
Commit hash: <none>
Traceback (most recent call last):
  File "/Users/sanch/.tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v1.2.0/lib/./launch.py", line 369, in <module>
    prepare_environment()
  File "/Users/sanch/.tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v1.2.0/lib/./launch.py", line 302, in prepare_environment
    git_clone(stable_diffusion_repo, repo_dir('stable-diffusion-stability-ai'), "Stable Diffusion", stable_diffusion_commit_hash)
  File "/Users/sanch/.tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v1.2.0/lib/./launch.py", line 157, in git_clone
    current_hash = run(f'"{git}" -C "{dir}" rev-parse HEAD', None, f"Couldn't determine {name}'s hash: {commithash}").strip()
  File "/Users/sanch/.tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v1.2.0/lib/./launch.py", line 111, in run
    raise RuntimeError(message)
RuntimeError: Couldn't determine Stable Diffusion's hash: cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf.
Command: "git" -C "/Users/sanch/.tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v1.2.0/lib/repositories/stable-diffusion-stability-ai" rev-parse HEAD
Error code: 128
stdout: <empty>
stderr: fatal: not a git repository (or any of the parent directories): .git
```
 I get a similar error when trying to run this package using `cli`. 
```sh
$ stable-diffusion-webui
/Users/sanch/.tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v*/entrypoint.sh: line 22: kill: (55942) - No such process
webui process died!

$ stable-diffusion-webui
Python 3.10.11 (main, Apr 20 2023, 20:33:22) [Clang 14.0.0 (clang-1400.0.29.202)]
Version: <none>
Commit hash: <none>
Traceback (most recent call last):
  File "/Users/sanch/.tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v1.2.0/lib/./launch.py", line 369, in <module>
    prepare_environment()
  File "/Users/sanch/.tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v1.2.0/lib/./launch.py", line 302, in prepare_environment
    git_clone(stable_diffusion_repo, repo_dir('stable-diffusion-stability-ai'), "Stable Diffusion", stable_diffusion_commit_hash)
  File "/Users/sanch/.tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v1.2.0/lib/./launch.py", line 157, in git_clone
    current_hash = run(f'"{git}" -C "{dir}" rev-parse HEAD', None, f"Couldn't determine {name}'s hash: {commithash}").strip()
  File "/Users/sanch/.tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v1.2.0/lib/./launch.py", line 111, in run
    raise RuntimeError(message)
RuntimeError: Couldn't determine Stable Diffusion's hash: cf1d67a6fd5ea1aa600c4df58e5b47da45f6bdbf.
Command: "git" -C "/Users/sanch/.tea/github.com/AUTOMATIC1111/stable-diffusion-webui/v1.2.0/lib/repositories/stable-diffusion-stability-ai" rev-parse HEAD
Error code: 128
stdout: <empty>
stderr: fatal: not a git repository (or any of the parent directories): .git
```

**Comment by mxcl** [comment]
our `test` node in that package needs to be more thorough. Seemingly they changed how the web ui works and we auto built it.

**Comment by mxcl** [comment]
fixed it, you need to uninstall/reinstall tho
