### ISSUE TITLE
🐞 gpt-engineer does not accept my API key via the gui terminal

### ISSUE THREAD

**Issue by sanchitram1** [pkgxdev/pantry#2662]
tried my personal key, created a new key as well, but still no results.

```sh
You need an OpenAI API key to use this package.
  
  > https://platform.openai.com/account/api-keys
  
  GPT4 is recommended (but you gotta sign up for the
  the [waitlist](https://openai.com/waitlist/gpt-4-api))
  
  **this key will not be persisted by tea!**

$ I provided my key here
  
  what do you want to build?
  
  the example prompt  gpt-engineer  provide is:
  
  │ we are writing snake in python. MVC components split in separate files. keyboard control.
  
  type your prompt below (⌃D when done)

$ I entered my prompt here
  
  we store the results in your documents folder, what’s the title?
  
  │ output will be written to  /Users/sanch/Documents/GPT Engineer/homebrew-created-at 
  
  
  running  gpt-engineer 
Traceback (most recent call last):

  File "/Users/sanch/.tea/github.com/AntonOsika/gpt-engineer/v0.0.7/venv/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/Users/sanch/.tea/github.com/AntonOsika/gpt-engineer/v0.0.7/venv/lib/python3.11/site-packages/gpt_engineer/main.py", line 44, in main
    ai = AI(
         ^^^

  File "/Users/sanch/.tea/github.com/AntonOsika/gpt-engineer/v0.0.7/venv/lib/python3.11/site-packages/gpt_engineer/ai.py", line 13, in __init__
    openai.Model.retrieve(model)

  File "/Users/sanch/.tea/github.com/AntonOsika/gpt-engineer/v0.0.7/venv/lib/python3.11/site-packages/openai/api_resources/abstract/api_resource.py", line 20, in retrieve
    instance.refresh(request_id=request_id, request_timeout=request_timeout)

  File "/Users/sanch/.tea/github.com/AntonOsika/gpt-engineer/v0.0.7/venv/lib/python3.11/site-packages/openai/api_resources/abstract/api_resource.py", line 32, in refresh
    self.request(

  File "/Users/sanch/.tea/github.com/AntonOsika/gpt-engineer/v0.0.7/venv/lib/python3.11/site-packages/openai/openai_object.py", line 172, in request
    requestor = api_requestor.APIRequestor(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/sanch/.tea/github.com/AntonOsika/gpt-engineer/v0.0.7/venv/lib/python3.11/site-packages/openai/api_requestor.py", line 138, in __init__
    self.api_key = key or util.default_api_key()
                          ^^^^^^^^^^^^^^^^^^^^^^

  File "/Users/sanch/.tea/github.com/AntonOsika/gpt-engineer/v0.0.7/venv/lib/python3.11/site-packages/openai/util.py", line 186, in default_api_key
    raise openai.error.AuthenticationError(

openai.error.AuthenticationError: No API key provided. You can set your API key in code using 'openai.api_key = <API-KEY>', or you can set the environment variable OPENAI_API_KEY=<API-KEY>). If your API key is stored in a file, you can point the openai module at it with 'openai.api_key_path = <PATH>'. You can generate API keys in the OpenAI web interface. See https://platform.openai.com/account/api-keys for details.
```

**Comment by sanchitram1** [comment]
got added to the tea org, but the same API key won't work.  with the GPT4 api key, I think you have to specify a header of your organization?

**Comment by jhheider** [comment]
does it work with `OPENAI_API_KEY=... gpt-engineer` in a terminal? if so, we should move this to `teaxyz/gui`.

**Comment by sanchitram1** [comment]
checking

**Comment by sanchitram1** [comment]
different error for that.  it's not able to identify the main prompt that I have in my `my-new-project`.  I was working through the example that they offered [here](https://github.com/AntonOsika/gpt-engineer/blob/19a4c10b6e61bf431e5ca7f6cd68a892b3fee122/README.md?plain=1#L46C1-L52C144), and mimicked that project set up locally.  Do you think mimicking that project requires me to clone that repo as well?  

## Folder Directory

```sh
gpt-engineer
│
└── projects
    │
    ├── example
    └── my-new-projects
        ├── prompt.txt
```

## Specific Error I am getting
```sh
$ gpt-engineer projects/my-new-project -v

DEBUG:openai:message='Request to OpenAI API' method=get path=https://api.openai.com/v1/models/gpt-4
DEBUG:openai:api_version=None data=None message='Post details'
DEBUG:urllib3.util.retry:Converted retries value: 2 -> Retry(total=2, connect=None, read=None, redirect=None, status=None)
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): api.openai.com:443
DEBUG:urllib3.connectionpool:https://api.openai.com:443 "GET /v1/models/gpt-4 HTTP/1.1" 200 None
DEBUG:openai:message='OpenAI API response' path=https://api.openai.com/v1/models/gpt-4 processing_ms=26 request_id=c7547ecd11c8d2c1b8281a9f9dac7d9a response_code=200
Traceback (most recent call last):

  File "/Users/sanch/.tea/github.com/AntonOsika/gpt-engineer/v0.0.7/venv/bin/gpt-engineer", line 8, in <module>
    sys.exit(app())
             ^^^^^

  File "/Users/sanch/.tea/github.com/AntonOsika/gpt-engineer/v0.0.7/venv/lib/python3.11/site-packages/gpt_engineer/main.py", line 64, in main
    messages = step(ai, dbs)
               ^^^^^^^^^^^^^

  File "/Users/sanch/.tea/github.com/AntonOsika/gpt-engineer/v0.0.7/venv/lib/python3.11/site-packages/gpt_engineer/steps.py", line 62, in gen_spec
    ai.fsystem(f"Instructions: {dbs.input['main_prompt']}"),
                                ~~~~~~~~~^^^^^^^^^^^^^^^

  File "/Users/sanch/.tea/github.com/AntonOsika/gpt-engineer/v0.0.7/venv/lib/python3.11/site-packages/gpt_engineer/db.py", line 21, in __getitem__
    raise KeyError(key)

KeyError: 'main_prompt'
```

**Comment by jhheider** [comment]
if you read their help, they default to the `./example/main_prompt`. you can pass it the directory on the command line, but the file _has_ to be `main_prompt`, afaik.

**Comment by jhheider** [comment]
this should work:
```shell
echo "write a program for me" >main_prompt
gpt-engineer .
```

**Comment by sanchitram1** [comment]
I cannot believe this worked, I tried main_prompt.txt, prompt.txt, and just prompt last night 🤦🏾  

Point is, `gpt-engineer .` wherever you have the main_prompt works.  Let me try on the gui again, and make an issue there if it doesn't work.
