### ISSUE TITLE
Not in pantry: khronos.org∕opencl-headers

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#2747]
Am I understanding this correctly? Why might this happen? What would I check next?

```
> ls -l /opt/tea/khronos.org/opencl-headers
total 0
lrwxr-xr-x  1 u0076374  staff   10 Aug  5 19:58 v* -> v2023.4.17
lrwxr-xr-x  1 u0076374  staff   10 Aug  5 19:58 v2023 -> v2023.4.17
lrwxr-xr-x  1 u0076374  staff   10 Aug  5 19:58 v2023.4 -> v2023.4.17
drwxr-xr-x  4 u0076374  staff  128 Aug  5 19:58 v2023.4.17

> pkg search khronos.org/opencl-headers
khronos.org/opencl-headers: 2023.4.17

> pkg build khronos.org/opencl-icd-loader
error: Uncaught Error: Not in pantry: khronos.org∕opencl-headers

https://github.com/teaxyz/pantry#contributing
      throw new TeaError('not-found: pantry: package.yml', {project}, )
            ^
    at https://deno.land/x/libtea@v0.6.2/src/hooks/usePantry.ts:49:13
    at project (https://deno.land/x/libtea@v0.6.2/src/hooks/usePantry.ts:50:5)
    at Object.getDeps (file:///opt/tea/tea.xyz/brewkit/v0.44.1/lib/usePantry.ts:30:21)
    at file:///opt/tea/tea.xyz/brewkit/v0.44.1/libexec/sort.ts:24:29
    at ascend (https://deno.land/x/libtea@v0.6.2/src/plumbing/hydrate.ts:62:31)
    at ascend (https://deno.land/x/libtea@v0.6.2/src/plumbing/hydrate.ts:88:19)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async go (https://deno.land/x/libtea@v0.6.2/src/plumbing/hydrate.ts:93:5)
    at async hydrate (https://deno.land/x/libtea@v0.6.2/src/plumbing/hydrate.t
```

**Comment by jhheider** [comment]
`tea -S` to sync pantry? or `export TEA_PANTRY_PATH="path/to/a/pantry/with/that/formula"`.

**Comment by mxcl** [comment]
that's a very old libtea, could be a parsing error is getting subsumed into an incorrect error, though that doesn't feel right.

**Comment by mxcl** [comment]
push the PR then we can try and repro?

**Comment by jhheider** [comment]
> khronos.org∕opencl-headers

That's not a `/`, it's a `∕`. Re-type it from your keyboard in your dependency list. It's the extended UTF-8 character used in place of path separators in filenames to prevent directory nesting.

**Comment by jhheider** [comment]
(noticed by looking at the issue title)

**Comment by magnusviri** [comment]
LOL. 🤦‍♂️

**Comment by mxcl** [comment]
like, this is my bad. I had to use weird unicode separators for some stuff because I'm mxcl. sorry.

**Comment by jhheider** [comment]
> because I'm mxcl

can confirm.
