### ISSUE TITLE
`tea -X gh` doesn't return github.com/cli/cli:bin/gh

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/pantry#28]
```sh
DEBUG=1 tea -X gh
{
  args: { args: [ "gh" ], pkgs: [], mode: "eXec" },
  flags: {
    verbosity: 2,
    magic: true,
    json: false,
    numpty: false,
    sync: false,
    verbose: true,
    debug: true,
    muggle: false,
    silent: false
  }
}
/Users/jacob/.tea/tea.xyz/v0.13.11/bin/tea
tea: resolving package graph
{ readYAML: "/Users/jacob/.tea/tea.xyz/var/pantry/projects/deno.land/package.yml" }
{ readYAML: "/Users/jacob/.tea/tea.xyz/var/pantry/projects/deno.land/package.yml" }
{
  installations: [
    { path: ~/.tea/deno.land/v1.28.1, pkg: { project: "deno.land", version: 1.28.1 } },
    { path: ~/.tea/deno.land/v1.28.2, pkg: { project: "deno.land", version: 1.28.2 } }
  ],
  versions: [ 1.28.1, 1.28.2 ],
  version: 1.28.2
{
  cwd: undefined,
  cmd: [ "gh" ],
  env: {
    PATH: "/Users/jacob/.tea/deno.land/v1.28.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin",
    LDFLAGS: "-Wl,-rpath,/Users/jacob/.tea",
    TEA_PREFIX: "/Users/jacob/.tea",
    SRCROOT: "/Users/jacob/tea/pantry.core"
  }
}
NotFound: No such file or directory (os error 2)
    at opRun (deno:runtime/js/40_process.js:33:16)
    at Object.run (deno:runtime/js/40_process.js:116:17)
    at run (file:///opt/tea.xyz/src/v0.13.11/src/utils/index.ts:176:21)
    at exec (file:///opt/tea.xyz/src/v0.13.11/src/app.exec.ts:199:23)
    at async default (file:///opt/tea.xyz/src/v0.13.11/src/app.exec.ts:24:9)
    at async X (file:///opt/tea.xyz/src/v0.13.11/src/app.X.ts:37:5)
    at async file:///opt/tea.xyz/src/v0.13.11/src/app.ts:34:9
```

**Comment by mxcl** [comment]
worksforme, per chance did you not `--sync` first?

```sh
$ tea -X gh
tea: installed: ~/.tea/github.com/cli/cli/v2.20.2
Work seamlessly with GitHub from the command line.

USAGE
  gh <command> <subcommand> [flags]

# [snip]
```

**Comment by jhheider** [comment]
Seems incredible, but possibly yes. Le sigh. Might need some UX and a .lastSynched file, lest we see more tickets like this (and I should know better).

**Comment by mxcl** [comment]
Yeah I think we'll want to suggest `--sync` for such errors pretty soon. If that was the issue. May well have been that `-X` was broken since it was barely a week ago that I rewrote the whole thing.
