### ISSUE TITLE
openssl version conflict while building

### ISSUE THREAD

**Issue by tannevaled** [pkgxdev/pantry#3587]
Hi,

i can load openssl^3 while i am out of the pantry tree.
i try to build with a dependency on openssl^3, but it seems brewkit have a dependency on openssl ^1.
```bash
PKG_CONFIG_PATH=/home/dd/.pkgx/openssl.org/v1.1.1w/lib/pkgconfig ...
PKGX_PKGENV=openssl.org=1.1.1w ...
LIBRARY_PATH=/home/dd/.pkgx/openssl.org/v1.1.1w/lib ...
LD_LIBRARY_PATH=/home/dd/.pkgx/openssl.org/v1.1.1w/lib ...
CPATH=/home/dd/.pkgx/openssl.org/v1.1.1w/include ...
```
```bash
$ pkg build github.com/jetporch/jetporch
error: Uncaught Error: cannot intersect: >=3.1.3 && ^1
  if (set.length <= 0) throw new Error(`cannot intersect: ${a} && ${b}`)
                             ^
    at Module.intersect (https://deno.land/x/libpkgx@v0.14.1/src/utils/semver.ts:383:30)
    at hydrate (https://deno.land/x/libpkgx@v0.14.1/src/plumbing/hydrate.ts:84:48)
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///home/dd/.pkgx/pkgx.sh/brewkit/v0.46.4/libexec/sort.ts:23:13
```
what is the standard way to do it?

Thanks in advance.

**Comment by jhheider** [comment]
This appears to be cargo requiring openssl.org^1; the comment suggests this is just for certs. So, it might able to be openssl.org '*' or even just ca-certs. Let me see about fixing this.
