### ISSUE TITLE
build failure: yarnpkg.com=4.1.0 (also: openssl and makotemplates)

### ISSUE THREAD

**Issue by jhheider** [pkgxdev/pantry#5056]
https://github.com/pkgxdev/pantry/actions/runs/7713901738/job/21035050769
https://github.com/pkgxdev/pantry/actions/runs/7712714539
https://github.com/pkgxdev/pantry/actions/runs/7712714516
https://github.com/pkgxdev/pantry/actions/runs/7712714507
https://github.com/pkgxdev/pantry/actions/runs/7712139542

requires https://github.com/pkgxdev/brewkit/pull/297

**Comment by jhheider** [comment]
@dosu-bot sure! brewkit is the piece used by pantry to build packages. the specific error is 
```
Run pkgxdev/brewkit/id@v1
Run if ! pkgx --sync; then

Run echo "::group::fetch deno deps"
fetch deno deps
Run ${GITHUB_ACTION_PATH}/id.ts yarnpkg.com=4.1.0
no versions parsed. Re-run with DEBUG=1 to see output.
{ versions: [] }
error: Uncaught (in promise) Error: not-found: version: yarnpkg.com=4.1.0
    throw new Error(`not-found: version: ${utils.pkg.str(spec)}`)
          ^
    at Object.resolve (file:///home/runner/work/_actions/pkgxdev/brewkit/v1/lib/hooks/usePantry.ts:43:11)
    at eventLoopTick (ext:core/01_core.js:63:7)
    at async file:///home/runner/work/_actions/pkgxdev/brewkit/v1/lib/resolve-pkg.ts:28:19
    at async default (file:///home/runner/work/_actions/pkgxdev/brewkit/v1/lib/resolve-pkg.ts:12:37)
    at async file:///home/runner/work/_actions/pkgxdev/brewkit/v1/id/id.ts:[5](https://github.com/pkgxdev/pantry/actions/runs/7713901738/job/21035050769#step:5:6):[17](https://github.com/pkgxdev/pantry/actions/runs/7713901738/job/21035050769#step:5:20)
```
which is due to the following ticket: https://github.com/pkgxdev/brewkit/issues/296

```
this breaks /releases packages. happened in https://github.com/pkgxdev/brewkit/commit/317eeb6f38c60d047b933b544db2505a50b5fe63

diff --git a/lib/hooks/useGitHubAPI.ts b/lib/hooks/useGitHubAPI.ts
index 766d205..ac258f6 100644
--- a/lib/hooks/useGitHubAPI.ts
+++ b/lib/hooks/useGitHubAPI.ts
@@ -15,6 +15,7 @@ interface GHRelease {
   tag_name: string
   name: string
   created_at: Date
+  prerelease: boolean
 }
 
 export default function useGitHubAPI() {
@@ -63,10 +64,16 @@ async function *getVersionsLong({ user, repo, type }: GetVersionsOptions): Async
       page++
       const [json, rsp] = await GET2<GHRelease[]>(`https://api.github.com/repos/${user}/${repo}/releases?per_page=100&page=${page}`)
       if (!isArray(json)) throw new Error("unexpected json")
-      for (const version of json.map(({ tag_name, name, created_at }) => ({
-        version: type == 'releases/tags' ? tag_name : name,
-        tag: tag_name,
-        date: created_at }))) {
+      for (const {tag_name, created_at, prerelease} of json) {
+        if (prerelease) {
+          console.debug("ignoring prerelease", tag_name)
+          continue
+        }
+        const version = {
+          version: type == 'releases/tags' ? tag_name : name,
+          tag: tag_name,
+          date: created_at
+        }
         yield version
       }
seems like deno should complain about name not being initialized, but it doesn't. weird.
```

**Comment by jhheider** [comment]
@dosu-bot: if you look at the diff, you'll see the `name` variable is no longer being extracted from the API response; since `name` is used if the `type == 'releases'` rather than `releases/tags`, it is getting set to `undefined`, resulting in the version not being found. that is fixed by https://github.com/pkgxdev/brewkit/pull/297

**Comment by jhheider** [comment]
fix confirmed.
