### ISSUE TITLE
xpra: Namespace GLib not available

### ISSUE THREAD

**Issue by sebst** [pkgxdev/pantry#7434]
```
vscode ➜ /workspaces/testcontainer/testbed-xpra $ xpra
 ✓  ~/.pkgx/info-zip.org/zip/v3.0.0
 ✓  ~/.pkgx/freedesktop.org/fontconfig/v2.14.1
 ✓  ~/.pkgx/x.org/xtst/v1.2.5
 ✓  ~/.pkgx/x.org/xi/v1.8.2
 ✓  ~/.pkgx/pcre.org/v8.45.0
 ✓  ~/.pkgx/oberhumer.com/lzo/v2.10.0
 ✓  ~/.pkgx/x.org/xfixes/v6.0.1
 ✓  ~/.pkgx/lz4.org/v1.10.0
 ✓  ~/.pkgx/x.org/xrender/v0.9.11
 ✓  ~/.pkgx/gnome.org/libxslt/v1.1.42
 ✓  ~/.pkgx/x.org/xrandr/v1.5.4
 ✓  ~/.pkgx/graphite.sil.org/v1.3.14
 ✓  ~/.pkgx/x.org/xdamage/v1.1.6
 ✓  ~/.pkgx/x.org/xshmfence/v1.3.2
 ✓  ~/.pkgx/x.org/xxf86vm/v1.1.5
 ✓  ~/.pkgx/gnu.org/fribidi/v1.0.16
 ✓  ~/.pkgx/xkbcommon.org/v1.7.0
 ✓  ~/.pkgx/x.org/pciaccess/v0.17.0
 ✓  ~/.pkgx/x.org/libxres/v1.2.2
 ✓  ~/.pkgx/x.org/xkbfile/v1.1.3
 ✓  ~/.pkgx/gnu.org/bison/v3.8.2
 ✓  ~/.pkgx/libjpeg-turbo.org/v2.1.5.1
 ✓  ~/.pkgx/x.org/xcomposite/v0.4.6
 ✓  ~/.pkgx/cairographics.org/pycairo/v1.26.1
 ✓  ~/.pkgx/intel.com/libva/v2.22.0
 ✓  ~/.pkgx/freedesktop.org/vdpau/v1.5.0
 ✓  ~/.pkgx/wayland.freedesktop.org/protocols/v1.37.0
 ✓  ~/.pkgx/wayland.freedesktop.org/v1.23.1
 ✓  ~/.pkgx/dri.freedesktop.org/v2.4.123
 ✓  ~/.pkgx/gnome.org/PyGObject/v3.50.0
 ✓  ~/.pkgx/gnu.org/m4/v1.4.19
 ✓  ~/.pkgx/ijg.org/v9f
 ✓  ~/.pkgx/freedesktop.org/dbus/v1.15.10
 ✓  ~/.pkgx/github.com/anholt/libepoxy/v1.5.10
 ✓  ~/.pkgx/ebassi.github.io/graphene/v1.10.8
 ✓  ~/.pkgx/freedesktop.org/icon-theme/v0.18.0
 ✓  ~/.pkgx/gnome.org/atk/v2.38.0
 ✓  ~/.pkgx/cairographics.org/v1.18.2
 ✓  ~/.pkgx/x.org/xv/v1.0.12
 ✓  ~/.pkgx/github.com/Cyan4973/xxHash/v0.8.2
 ✓  ~/.pkgx/gnome.org/pango/v1.54.0
 ✓  ~/.pkgx/harfbuzz.org/v8.5.0
 ✓  ~/.pkgx/gnome.org/libxml2/v2.13.4
 ✓  ~/.pkgx/facebook.com/zstd/v1.5.6
 ✓  ~/.pkgx/kerberos.org/v1.21.3
 ✓  ~/.pkgx/freedesktop.org/at-spi2-atk/v2.38.0
 ✓  ~/.pkgx/pcre.org/v2/v10.44.0
 ✓  ~/.pkgx/github.com/lm-sensors/lm-sensors/v3.6.0
 ✓  ~/.pkgx/github.com/westes/flex/v2.6.4
 ✓  ~/.pkgx/pixman.org/v0.40.0
 ✓  ~/.pkgx/elfutils.org/v0.191.0
 ✓  ~/.pkgx/gnome.org/gobject-introspection/v1.72.0
 ✓  ~/.pkgx/gnome.org/gsettings-desktop-schemas/v47.1.0
 ✓  ~/.pkgx/freedesktop.org/shared-mime-info/v2.4.0
 ✓  ~/.pkgx/webmproject.org/libvpx/v1.14.1
 ✓  ~/.pkgx/freedesktop.org/XKeyboardConfig/v2.42.0
 ✓  ~/.pkgx/videolan.org/x264/v0.164.3095
 ✓  ~/.pkgx/github.com/AOMediaCodec/libavif/v1.1.1
 ✓  ~/.pkgx/gnu.org/gettext/v0.21.1
 ✓  ~/.pkgx/khronos.org/glslang/v15.0.0
 ✓  ~/.pkgx/openprinting.github.io/cups/v2.4.10
 ✓  ~/.pkgx/gnome.org/gdk-pixbuf/v2.42.9
 ✓  ~/.pkgx/debian.org/iso-codes/v4.17.0
 ✓  ~/.pkgx/aomedia.googlesource.com/aom/v3.10.0
 ✓  ~/.pkgx/mesa3d.org/v24.2.3
 ✓  ~/.pkgx/gnome.org/glib/v2.82.1
 ✓  ~/.pkgx/cython.org/v3.0.11
 ✓  ~/.pkgx/gtk.org/gtk3/v3.24.38
 ✓  ~/.pkgx/xpra.org/v6.1.2
 ✓  ~/.pkgx/unicode.org/v71.1.0
 ✓  ~/.pkgx/python.org/v3.11.10
 ✓  ~/.pkgx/llvm.org/v19.1.0
xpra main error:
Traceback (most recent call last):
  File "/home/vscode/.pkgx/xpra.org/v6.1.2/venv/lib/python3.11/site-packages/xpra/scripts/main.py", line 138, in main
    return run_mode(script_file, cmdline, err, options, args, mode, defaults)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vscode/.pkgx/xpra.org/v6.1.2/venv/lib/python3.11/site-packages/xpra/scripts/main.py", line 505, in run_mode
    set_name("Xpra", "Xpra %s" % mode.strip("_"))
  File "/home/vscode/.pkgx/xpra.org/v6.1.2/venv/lib/python3.11/site-packages/xpra/platform/__init__.py", line 139, in set_name
    set_prgname(prgname or _prgname)
  File "/home/vscode/.pkgx/xpra.org/v6.1.2/venv/lib/python3.11/site-packages/xpra/platform/__init__.py", line 149, in set_prgname
    GLib = gi_import("GLib")
           ^^^^^^^^^^^^^^^^^
  File "/home/vscode/.pkgx/xpra.org/v6.1.2/venv/lib/python3.11/site-packages/xpra/os_util.py", line 52, in gi_import
    gi.require_version(mod, version)
  File "/home/vscode/.pkgx/gnome.org/PyGObject/v3.50.0/lib/python3/site-packages/gi/__init__.py", line 122, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace GLib not available
```

**Comment by jhheider** [comment]
it looks like glib is missing an introspection repository. i'm building that now, but it doesn't seem to be fixing this specific issue.

**Comment by jhheider** [comment]
```shell
pkgx/work $ xpra
env +pkgx.sh/brewkit^0,^1 +git-scm.org
env +xpra && xpra 
env +pkgx.sh/brewkit^0,^1 +git-scm.org

Warning: running as root

Error: cannot show the xpra gui
 failed to initialize Gtk, no display?
 you must use this subcommand from a desktop environment
 from a terminal session you can try `xpra list`, `xpra showconfig`, etc
```
