### ISSUE TITLE
Can't `pipenv install torch`

### ISSUE THREAD

**Issue by magnusviri** [pkgxdev/pantry#754]
It looks like tea is doing things a little different. I'm trying to install torch, as part of the setup for [this project](https://github.com/ggerganov/llama.cpp). This is my setup.

```
tea +python.org~3.10.0 python --version # Make sure I have python 3.10 installed because I don't think 3.11 has torch yet
mkdir llama ; cd llama
pipenv --python ~/.tea/python.org/v3.10.8/bin/python
pipenv install torch numpy sentencepiece
```

This is the error I'm getting

```
Installing torch...
Resolving torch...
Installing...
⠴ Installing torch...[31m[1mError: [0m An error occurred while installing [32mtorch[0m!
Error text:
[36mERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
[0m
✘ Installation Failed
```

I could easily be doing something wrong. Anyway, I thought I'd post this to get it started.

**Comment by magnusviri** [comment]
It looks like this works:

```
pip --python ~/.tea/python.org/v3.10.8/bin/python install torch numpy sentencepiece
```

I didn't let it finish running. However, I was hoping to put it in a venv with pipenv.

**Comment by jhheider** [comment]
What about `tea +python.org~3.10 pipenv install torch numpy sentencepiece`? That's what I'd expect to work, if I weren't in a (`tea`) venv.

**Comment by mxcl** [comment]
IIRC this is a python issue. Torch requires Python 3.11.

**Comment by magnusviri** [comment]
Right now only Pytorch nightly runs in Python 3.11. [See this thread](https://discuss.pytorch.org/t/pytorch-does-not-support-python-3-11/173747). This project page only lists 3.10 as the latest python version (search for "Programming Language", on the [left side of page](https://pypi.org/project/torch/)).

```
> pip --python ~/.tea/python.org/v3.10.8/bin/python install torch
Collecting torch
  Using cached torch-1.13.1-cp310-none-macosx_11_0_arm64.whl (53.2 MB)
Requirement already satisfied: typing-extensions in ~/.tea/python.org/v3.10.8/lib/python3.10/site-packages (from torch) (4.5.0)
Installing collected packages: torch
Successfully installed torch-1.13.1
> pip --python ~/.tea/python.org/v3.11.1/bin/python install torch
ERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
```

**Comment by magnusviri** [comment]
I think the problem is that tea's 3.10 doesn't include pipenv...

```
tea +python.org~3.10.8 +pipenv.pypa.io pipenv install torch
Traceback (most recent call last):
  File "/opt/tea/pipenv.pypa.io/v2023.2.18/venv/bin/pipenv", line 5, in <module>
    from pipenv import cli
ModuleNotFoundError: No module named 'pipenv'
```

Was pipenv added to python in 3.11?

**Comment by magnusviri** [comment]
I don't think that's the problem. If I install pipenv into 3.10.8, I still get the same error.

```
> tea +python.org~3.10.8 +pip.pypa.io pip install pipenv
Collecting pipenv
  Downloading pipenv-2023.2.18-py3-none-any.whl (2.9 MB)
...
Installing collected packages: distlib, virtualenv-clone, setuptools, platformdirs, filelock, certifi, virtualenv, pipenv
Successfully installed certifi-2022.12.7 distlib-0.3.6 filelock-3.9.1 pipenv-2023.2.18 platformdirs-3.1.1 setuptools-67.6.0 virtualenv-20.21.0 virtualenv-clone-0.5.7

> tea +python.org~3.10.8 +pipenv.pypa.io pipenv install torch
Installing torch...
Resolving torch...
Installing...
⠙ Installing torch...[31m[1mError: [0m An error occurred while installing [32mtorch[0m!
Error text:
[36mERROR: Could not find a version that satisfies the requirement torch (from versions: none)
ERROR: No matching distribution found for torch
[0m
✘ Installation Failed
```

**Comment by magnusviri** [comment]
I finally got it to work. I don't know why this got it to work. I deleted /opt/tea/{python.org,pipenv.pypa.io,pip.pypa.io} and /Users/james/.local/share/virtualenvs/bla* before running to make sure it was a clean environment. I tried both /opt/tea and ~/.tea and they both work.

```
> tea +python.org~3.10.8 +pipenv.pypa.io python -m pipenv --python /opt/tea/python.org/v3.10.8/bin/python install torch
installed: /opt/tea/python.org/v3.10.8
installed: /opt/tea/pipenv.pypa.io/v2023.2.18
/opt/tea/python.org/v3.10.8/bin/python: No module named pipenv

> tea +python.org~3.10.8 +pip.pypa.io python -m pip install pipenv
installed: /opt/tea/pip.pypa.io/v23.0.1
Collecting pipenv
  Using cached pipenv-2023.2.18-py3-none-any.whl (2.9 MB)
...
Installing collected packages: distlib, virtualenv-clone, setuptools, platformdirs, filelock, certifi, virtualenv, pipenv
Successfully installed certifi-2022.12.7 distlib-0.3.6 filelock-3.9.1 pipenv-2023.2.18 platformdirs-3.1.1 setuptools-67.6.0 virtualenv-20.21.0 virtualenv-clone-0.5.7

> tea +python.org~3.10.8 +pipenv.pypa.io python -m pipenv --python /opt/tea/python.org/v3.10.8/bin/python install torch
Creating a virtualenv for this project...
Pipfile: `/Users/james/ai/`bla/Pipfile
Using /opt/tea/python.org/v3.10.8/bin/python (3.10.8) to create virtualenv...
⠙ Creating virtual environment...created virtual environment CPython3.10.8.final.0-64 in 147ms
  creator CPython3Posix(dest=/Users/james/.local/share/virtualenvs/bla-jILoI7h4, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/james/Library/Application Support/virtualenv)
    added seed packages: pip==23.0.1, setuptools==67.4.0, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/james/.local/share/virtualenvs/bla-jILoI7h4
Installing torch...
Resolving torch...
Installing...
Adding torch to Pipfile's [packages] ...
✔ Installation Succeeded
Installing dependencies from Pipfile.lock (fd6d7d)...
```

**Comment by magnusviri** [comment]
I narrowed it down to the name of one directory: /opt/tea/pipenv.pypa.io/v2023.2.18/venv/lib/python3.11/.

From a completely clean environment.

```
> tea +python.org~3.10.8 +pipenv.pypa.io pipenv --python 3.10.8 install torch
installed: /opt/tea/python.org/v3.10.8
installed: /opt/tea/pipenv.pypa.io/v2023.2.18
Traceback (most recent call last):
  File "/opt/tea/pipenv.pypa.io/v2023.2.18/venv/bin/pipenv", line 5, in <module>
    from pipenv import cli
ModuleNotFoundError: No module named 'pipenv'

> mv /opt/tea/pipenv.pypa.io/v2023.2.18/venv/lib/python3.11 /opt/tea/pipenv.pypa.io/v2023.2.18/venv/lib/python3.10

> tea +python.org~3.10.8 +pipenv.pypa.io pipenv --python 3.10.8 install torch
Creating a virtualenv for this project...
Pipfile: /Users/james/ai/bla/Pipfile
Using /opt/tea/pipenv.pypa.io/v2023.2.18/venv/bin/python3 (3.10.8) to create virtualenv...
⠹ Creating virtual environment...created virtual environment CPython3.10.8.final.0-64 in 189ms
  creator CPython3Posix(dest=/Users/james/.local/share/virtualenvs/bla-jILoI7h4, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/Users/james/Library/Application Support/virtualenv)
    added seed packages: pip==23.0.1, setuptools==67.4.0, wheel==0.38.4
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator

✔ Successfully created virtual environment!
Virtualenv location: /Users/james/.local/share/virtualenvs/bla-jILoI7h4
Creating a Pipfile for this project...
Installing torch...
Resolving torch...
Installing...
Adding torch to Pipfile's [packages] ...
✔ Installation Succeeded
Pipfile.lock not found, creating...
Locking [packages] dependencies...
Building requirements...
Resolving dependencies...
✔ Success!
Locking [dev-packages] dependencies...
Updated Pipfile.lock (268e308202aad8b46ab886fbf2b011fa68905397af41f7857c9e3cd6cdf83062)!
Installing dependencies from Pipfile.lock (f83062)...
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
```

**Comment by mxcl** [comment]
You’re the expert on `pipenv` here @magnusviri, what should we do?

**Comment by magnusviri** [comment]
Wellll, I don't consider myself an expert on this at all, but I surprised myself by having an opinion. So until a real python expert shows up with a better idea, here is what I consider my "good enough" opinion.

Because tea supports python 3.10 and 3.11, I think pipenv and pip should be packaged so it works with both. If you ever add python 3.9, 3.8, etc., then pipenv and pip should similarly support them. I'm not sure how to do that, it might be as easy as adding the appropriately named folders and symlinks for those versions. I can test this.

It would be cool if tea ran code specific to the tool too. That is, if tea is asked to run pipenv or pip, tea could check for something like  `--python ([\d\.]+)` and automatically add +python.org~\1 or something like that. This would be a convenience and I'm not really that big on it, it was just an idea.

**Comment by mxcl** [comment]
k cool. I think we can make it behave better in this regard. Thanks for the input!

**Comment by mxcl** [comment]
so it's because the venv we have for pipenv requires python 3.11 or something?

**Comment by magnusviri** [comment]
I think I fixed this simply by creating a link.

```
> cd ~/.tea/pipenv.pypa.io/v2023.2.18/venv/lib
> ln -s python3.11 python3.10
> cd
> mkdir test
> cd test
> tea +python.org~3.10.8 +pipenv.pypa.io pipenv shell --python 3.10.8
(test) > python --version
Python 3.10.8
```

**Comment by mxcl** [comment]
I believe the problem is:

* pipenv needs a python
* that python doesn't have to be the python it uses for the envs it creates

We probably have to hack pipenv to be `tea` aware, or potentially tea itself should replace pipenv altogether. I have to dive deep.

**Comment by mxcl** [comment]
k so: https://pipenv.pypa.io/en/latest/specifiers/#specifying-versions-of-python

we need to hack pipenv to auto install the requested pythons IMO. Which would make us the best way to use pipenv too.

**Comment by magnusviri** [comment]
Do you mean that `tea +python.org^3.10.0 pipenv` would run `pipenv –python 3.10` or something like that? That would mean modifying [python-venv.sh](https://github.com/teaxyz/brewkit/blob/main/share/brewkit/python-venv.sh), wouldn't it? Or would you make the change in the cli itself?

**Comment by mxcl** [comment]
```sh
$ pipenv --python 3.7
tea: installing python^3.7
# …
```
